### ISSUE TITLE
Catch groovyx.net.http.HttpResponseException IFTTT

### ISSUE THREAD

**Issue by hammad93** [SmartThingsCommunity/SmartThingsPublic#41966]
https://github.com/SmartThingsCommunity/SmartThingsPublic/blob/8706969e0713bd135590d830b48324045a5c39b8/smartapps/smartthings/ifttt.src/ifttt.groovy#L257

An exception was not caught here that has caused an outage as discussed here, https://community.smartthings.com/t/ifttt-and-webcore-not-working-25-aug-2020/

**Comment by tpmanley** [comment]
Thanks for flagging @hammad93 . Our team reached out to IFTTT and it appears to have been an issue on their end which they have since resolved https://status.ifttt.com/. I don't think catching the `HttpResponseException` would have prevented the problem since it was an error on their end and I don't think there is anything we could have done in the exception handler to make it work.
